spring:
  application:
    name: distributed-rate-limitter
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

rate-limiter:
  algorithm: token-bucket

token:
  bucket:
    bucket-capacity: 100
    refill-rate-per-second: 10

sliding:
  window:
    window-size-in-seconds: 60
    max-requests: 100
management:
  server:
    port: 8080
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics, thread-dump

---
spring:
  config:
    activate:
      on-profile: redis

  docker:
    compose:
      enabled: true
      profiles:
        active: "redis"

management:
  health:
    redis:
      enabled: true
