spring:
  application:
    name: distributed-rate-limitter

server:
  port: 8080

token:
  bucket:
    bucketCapacity: 100
    refillRatePerSecond: 10
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics, thread-dump